# Generated by Django 5.0.1 on 2024-02-26 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.CreateModel(
            name='InboxEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('follow', 'Follow'), ('Like', 'Like')], max_length=10)),
                ('entry_json', models.JSONField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
