# Generated by Django 5.0.1 on 2024-02-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_last_modified'),
        ('api', '0002_remove_post_like_count_inboxentry'),
    ]

    operations = [
    ]
