# Generated by Django 5.0.1 on 2024-02-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.CharField(blank=True, default=' ', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
