# Generated by Django 5.0.1 on 2024-03-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_node_user_node_password_node_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(default=' ', max_length=400),
            preserve_default=False,
        ),
    ]
