# Generated by Django 5.0.1 on 2024-03-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_image'),
        ('api', '0009_author_host_author_url'),
    ]

    operations = [
    ]
