# Generated by Django 5.0.1 on 2024-03-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_inboxentry_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follow relationship',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followed', 'follower')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'author')},
        ),
    ]
