# Generated by Django 5.0.1 on 2024-03-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.CharField(blank=True, default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Png'), ('image/jpeg;base64', 'Jpeg')], default='text/plain', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Png'), ('image/jpeg;base64', 'Jpeg')], max_length=255),
        ),
    ]
