# Generated by Django 5.0.1 on 2024-03-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_author_profile_image_alter_comment_contenttype_and_more'),
        ('api', '0021_alter_comment_contenttype_alter_post_contenttype'),
    ]

    operations = [
    ]
