# Generated by Django 5.0.1 on 2024-03-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20240319_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='contentType',
        ),
    ]
