# Generated by Django 5.0.1 on 2024-03-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_comment_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
