# Generated by Django 5.0.1 on 2024-03-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_node_authors_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='authors_added',
        ),
    ]
