# Generated by Django 5.0.1 on 2024-03-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_post_image'),
        ('api', '0025_remove_node_authors_added'),
    ]

    operations = [
    ]
