# Generated by Django 5.0.1 on 2024-04-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_author_github_alter_author_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxentry',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
